### ISSUE TITLE
Support not only languages with basic Latin characters

### ISSUE THREAD

**Issue by azat-io** [ilyatitovich/remark-lint-heading-capitalization#12]
You have a regular expression in your code:

```js
const correctTitle = title.replace(/[^\s-]\w+/g, (word, index) => {
```

The problem is that the plugin doesn't work with languages with extended Latin (such as the special letters of the German alphabet) and Cyrillic. It is worth adding their support.

**Comment by ilyatitovich** [comment]
The plugin was developed following capitalization rules for titles written in English. I'm not sure if these rules apply to other languages. Adding the ability to increase the number of lowercase words is a good idea, but this plugin is mainly for linting English titles.

**Comment by ilyatitovich** [comment]
Added, thank for the feedback!
