### ISSUE TITLE
Ignore string support

### ISSUE THREAD

**Issue by literat** [ilyatitovich/remark-lint-heading-capitalization#13]
Hi,

I am implementing this heading capitalization lint and it is great.
But I am also struggling with some string in the headings which are not correctly recognized.

For example:

```md
# Contributing to `@lmc-eu/spirit-design-system`
```

Error:

```sh
1:1-1:49 warning Heading capitalization error. Expected: 'Contributing to @Lmc-Eu/Spirit-Design-System' found: 'Contributing to @lmc-eu/spirit-design-system' heading-capitalization remark-lint
```

In some places in my docs, I need to use a package name in a heading or some different string that I do not want to be capitalized.

I am aware that I can ignore comments like this:

```md
<!--lint disable heading-capitalization -->
# @lmc-eu/spirit-web
<!--lint enable heading-capitalization -->
```

But I am trying to find a more proper way to do this. I like the option `lowerCaseWords` but it cannot handle more complex strings like the package name.
Maybe it would be possible to split the headings by the empty space `' '` and check some array with ignored strings (new `ignore` option?) and then also split it by dash `-` and capitalize (https://github.com/ilyatitovich/remark-lint-heading-capitalization/blob/main/index.js#L10).

I would like to know your opinion first and then I can try to prepare a PR for this.

Thank you :-)

**Comment by ilyatitovich** [comment]
Hi, sorry for late response. IlI think it's rare case, so if you have any idea, feel free to send PR :)

**Comment by literat** [comment]
Thanks, I have sent the PR. You can check it out https://github.com/ilyatitovich/remark-lint-heading-capitalization/pull/14 :-)
